version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
  build_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm sependencies
          command: |
            npm install --save
  build_docker_test:
    docker: 
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build docker image
          command: |
            docker build -t nodewebapp -t anjalisoni12/nodewebapp:latest .
      - run:
          name: Docker login and push
          command: |
            echo $DOCKER_PASSWORD | docker login -u anjalisoni12 --password-stdin
            docker push anjalisoni12/nodewebapp:latest

workflows:
  build_test:
    jobs:
      - build_tests
      - build_docker_test
      - notify:
          requires:
            - build_tests
            - build_docker_test


